services:
  - type: web
    name: edvora-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: MODEL_NAME
        value: gpt-4
      - key: MAX_TOKENS
        value: 2000
      - key: TEMPERATURE
        value: 0.1
      - key: CHUNK_SIZE
        value: 800
      - key: CHUNK_OVERLAP
        value: 100
      - key: VECTOR_DIMENSION
        value: 1536
      - key: SIMILARITY_THRESHOLD
        value: 0.7
